name: CI

on: [push]
on:
  schedule:
    # * is a special character in YAML so you have to quote this string - 1 am
    - cron:  '0 1 * * *'
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: prepare
      run: |
        mkdir -p build
        cd build
        cmake ..
    - name: build
      run: |
        cd build
        cmake --build .
